name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Run tests
      run: ./gradlew test
      
    - name: Build APK
      run: ./gradlew assemble

    - name: Rename APKs for clarity
      run: |
        mkdir -p upload-apks
        find . -type f -name "*.apk" -exec cp {} upload-apks/ \;

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Carburoid-apk
        path: |
          upload-apks/
